name: Docker Image CI

on:
  push:
    branches: [ "aws" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: duyadmindocker/flow-pilot-be:latest

  deploy:
    needs: build
    runs-on: aws-ec2
    steps:
      - name: Pull image from Docker Hub
        run: docker pull duyadmindocker/flow-pilot-be:latest

      - name: Delete old container if exists
        run: docker rm -f flow-pilot-be-container || true

      - name: Run docker container
        run: docker container run -dp 4000:4000 --name flow-pilot-be-container duyadmindocker/flow-pilot-be:latest