name: Docker Image CI

on:
  push:
    branches: [ "aws" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login DockerHub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build -t duyadmindocker/flow-pilot-be .
    - name: Push to DockerHub
      run: docker push duyadmindocker/flow-pilot-be:latest
